### ISSUE TITLE
Cannot create repo, validation of git repo url does not pass

### ISSUE THREAD

**Issue by mn7z** [dogdep/dogpro#14]
Browser: Chrome 46.0.2490.86
dogpro version: 8b45cad82d5a3913d41c2fd7827eac03ba05c1df

Tried:
- ssh://git@bitbucket.org:mn7z/demo.git
- git@bitbucket.org:mn7z/demo.git
- git@github.com:dogdep/dogpro.git

Getting `Please match the requested format`

I have actually been able to enter the value **`ssh:/.git` as a valid one.**

The format `(?:git|ssh|https?|git@[\w\.]+):(?:\/\/)?[\w\.@:\/~_-]+\.git\/?` which can be found at `public/templates/repo` seems working great while testing in [regex online](https://regex101.com/#javascript), however the browser renders the field:

```
<input class="form-control ng-dirty ng-valid-parse ng-valid-required ng-touched ng-valid ng-valid-pattern"     type="text"   id="url" placeholder="GIT URL..." ng-model="repo.url" required="" title="This must be a valid GIT URL" pattern="(?:git|ssh|https?|git@[w.]+):(?://)?[w.@:/~_-]+.git/?">
```

**Comment by vaidasm** [comment]
Check removed completely in 5a8e060ea3aa856b3d7d3015e087c548c9021c1e
