### ISSUE TITLE
This can run in a production environment, please ？？

### ISSUE THREAD

**Issue by vTNT** [dogdep/dogpro#6]

**Comment by vaidasm** [comment]
What do you mean "can run in a production environment?". This project should help you deploy stuff to production environment.

**Comment by vTNT** [comment]
thanks

**Comment by vTNT** [comment]
root@ubuntu:~/sa/dogpro# docker-compose up -d  
Recreating dogpro_mysql_1
Recreating dogpro_artisan_1
WARNING: Service "artisan" is using volume "/var/www" from the previous container. Host mapping "/root/sa/dogpro" has no effect. Remove the existing containers (with `docker-compose rm artisan`) to use the host volume mapping.
Recreating dogpro_php_1
WARNING: Service "php" is using volume "/var/www" from the previous container. Host mapping "/root/sa/dogpro" has no effect. Remove the existing containers (with `docker-compose rm php`) to use the host volume mapping.
Recreating dogpro_webtools_1
Creating dogpro_web_1
ERROR: docker/nginx/nginx.conf includes invalid characters for a local volume name, only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

today , i try to install it,   how to solve it ?

**Comment by vTNT** [comment]
and  if  i use  Manual setup. i wil find this error 
 [2015-11-16 05:35:11] local.ERROR: exception 'ErrorException' with message 'Undefined index: _sf2_meta' in /var/www/vendor/laravel/framework/src/Illuminate/Session/Store.php:286
this is my .env about session:
##
# Drivers
##
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=database

**Comment by vaidasm** [comment]
Could you post your docker-compose.yml, docker version and output of docker info? I cannot replicate the error. 


On session error, looks like https://github.com/laravel/framework/issues/7586 

Could you try to change 
```
config()->set('session.driver', 'array');
```
line to 
```
config()->set('session.driver', null);
```
in `app/Http/Middleware/StartSessionOnlyForInternals.php` and let me know if it works?

**Comment by vTNT** [comment]
os: ubuntu 14.04         docker version:1.9.0   docker compose version:1.5.1
root@ubuntu:~/dockerfile# docker -v
Docker version 1.9.0, build 76d6bc9
root@ubuntu:~/dockerfile# docker info
Containers: 11
Images: 128
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 150
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 7.785 GiB
Name: ubuntu
--------------------------
root@ubuntu:~/dockerfile# docker-compose -v
docker-compose version: 1.5.1

**Comment by vaidasm** [comment]
This should fix the issue with docker compose:
https://github.com/dogdep/dogpro/commit/b5285e98aec040855cdef171dc4c5abee4aa832b

Just add change 
```
     - "docker/nginx/nginx.conf:/etc/nginx/sites-enabled/laravel.conf"
```
to 
```
     - "./docker/nginx/nginx.conf:/etc/nginx/sites-enabled/laravel.conf"
```

in `docker-compose.yml` and let me know if it workd

**Comment by vTNT** [comment]
nice!!!  i change to  - "./docker/nginx/nginx.conf:/etc/nginx/sites-enabled/laravel.conf",  docker-compose up -d  is ok,   thank u

**Comment by vTNT** [comment]
does it support stash ?? Our code is stored in stash

**Comment by vaidasm** [comment]
Authentication is only available with github/bitbucket/gitlab (or anything that is supported by [socialite](https://github.com/laravel/socialite))

The code can be stored in any git server, so once you have authenticated, you can add repositories from anywhere

**Comment by vTNT** [comment]
ok, thank u

**Comment by vTNT** [comment]
hi, before i use docker setup, it is ok.   
today, i try to Manual setup.  and  i change the code ‘config()->set('session.driver', 'array'); ’  to ' config()->set('session.driver', null); ', but i still find this error 
[2015-11-16 05:35:11] local.ERROR: exception 'ErrorException' with message 'Undefined index: _sf2_meta' in /var/www/vendor/laravel/framework/src/Illuminate/Session/Store.php:286
my os version is ubuntu 14.04, php version is php5.5.

**Comment by vTNT** [comment]
And I found this docker-compose.yml which has the following contents:  command: php /var/www/artisan queue:listen --tries=1 --timeout=360    but in Manual setup,  i cannot find that. Does this mean that the manual installation is not required to execute the command

**Comment by vaidasm** [comment]
php artisan queue:listen is for queue daemon, you can read more about it in [laravel docs](http://laravel.com/docs/5.1/queues#running-the-queue-listener)

**Comment by vaidasm** [comment]
Could you confirm this problem still exists in v1.0.1?

**Comment by vTNT** [comment]
it is ok thanks
