### ISSUE TITLE
Unable to release to Ubuntu

### ISSUE THREAD

**Issue by ValdasK** [dogdep/dogpro#8]
I get the following error when running deploy command:

TASK: [dogpro.deploy | DEPLOY | WRITABLE FILES] ******************************* 
failed: [ubuntu@52.17.255.177] => (item=app/cache) => {"changed": true, "item": "app/cache", "rc": 127}
stderr: OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 52.17.255.177 closed.

stdout: /home/ubuntu/.ansible/tmp/ansible-tmp-1448633786.51-127983444167259/writable.sh: line 5: setfacl: command not found
/home/ubuntu/.ansible/tmp/ansible-tmp-1448633786.51-127983444167259/writable.sh: line 6: setfacl: command not found

failed: [ubuntu@52.17.255.177] => (item=app/logs) => {"changed": true, "item": "app/logs", "rc": 127}
stderr: OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 52.17.255.177 closed.

stdout: /home/ubuntu/.ansible/tmp/ansible-tmp-1448633787.69-145433176063591/writable.sh: line 5: setfacl: command not found
/home/ubuntu/.ansible/tmp/ansible-tmp-1448633787.69-145433176063591/writable.sh: line 6: setfacl: command not found

FATAL: all hosts have already failed -- aborting`

**Comment by mn7z** [comment]
ref. [file permissions acl ubuntu](https://help.ubuntu.com/community/FilePermissionsACLs)

> It may be necessary to install acl utilities from the repositories. In the Server Edition, this must be done, but in the desktop editions acl is installed by default.

To install it: `sudo apt-get install acl`

**Comment by vaidasm** [comment]
fixed in f20b7e3624e1c974e6683aba8dc223949a10a472
